fProg:
	gcc fProg.c -o fProg.exe

fProgT:
	gcc fProgThreading.c -pthread -o fProgT.exe

sProg:
	gcc sProg.c -o sProg.exe

sProgT:
	gcc sProgThreading.c -pthread -o sProgT.exe

tProg:
	gcc tProg.c -o tProg.exe

tProgT:
	gcc tProgThreading.c -pthread -o tProgT.exe

clean:
	rm *.exe